---
# defaults file for node-preflight
ntp_server: "asia.pool.ntp.org"
timezone: "UTC"
dns_servers:
  - "1.1.1.1"
  - "8.8.8.8"
  - "9.9.9.9"
search_domain: "local"
security_enabled: true
firewall_enabled: true
swap_enabled: false
