---
# tasks file for node-preflight

- name: Load common variables
  ansible.builtin.include_vars: "common.yml"
  tags: [ always ]

- name: Load OS-family variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
  tags: [ always ]

- name: Update package caches
  become: true
  ansible.builtin.package:
    update_cache: true

- name: Include dns
  ansible.builtin.import_tasks: "dns.yml"

- name: Include chrony
  ansible.builtin.import_tasks: "chrony.yml"

- name: Include timezone
  ansible.builtin.import_tasks: "timezone.yml"

- name: Include disable security
  when: not (security_enabled | bool)
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "disable-security-{{ ansible_distribution }}.yml"
        - "disable-security-{{ ansible_os_family }}.yml"
      skip: true
  tags: [ always ]

- name: Include disable firewall
  when: not (firewall_enabled | bool)
  ansible.builtin.import_tasks: "disable-firewall.yml"

- name: Include disable swap
  when: not (swap_enabled | bool)
  ansible.builtin.import_tasks: "disable-swap.yml"

- name: Include check cgroupv2
  ansible.builtin.import_tasks: "cgroup.yml"

- name: Include ebpf requirement tasks for Alpine
  when: ansible_facts["os_family"] == "Alpine"
  ansible.builtin.import_tasks: "ebpf-Alpine.yml"
  tags: [ node-preflight, ebpf ]

- name: Finalize preflight (run handlers)
  ansible.builtin.meta: flush_handlers
  tags: [node-preflight]
