- name: Configure sysctl
  become: true
  tags: [ node_network, sysctl ]
  block:
    - name: Load sysctl configs persistently
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: true
      loop: "{{ sysctl_config | dict2items }}"
