---
#handlers file for node-preflight
- name: Include chrony handlers
  ansible.builtin.import_tasks: "chrony.yml"

- name: Include NetworkManager handlers
  ansible.builtin.import_tasks: "networkmanager.yml"
