- name: Control Plane Init
  when: inventory_hostname == groups['k8s_control_plane'][0]
  become: true
  block:
    - name: Write kubeadm config file on first control_plane
      when:
        - not kubernetes_joined
      ansible.builtin.template:
        src: kubeadm-config.yml.j2
        dest: /etc/kubernetes/kubeadm-config.yml
        owner: root
        group: root
        mode: "0644"

    - name: Initialize on first control_plane
      when:
        - not kubernetes_joined
      ansible.builtin.command: kubeadm init --upload-certs --config=/etc/kubernetes/kubeadm-config.yml

    - name: Generate join token
      ansible.builtin.command: kubeadm token generate
      register: join_token

    - name: Generate join command
      ansible.builtin.command: kubeadm token create --print-join-command {{ join_token.stdout }}
      register: join_command

    - name: Save join token 
      ansible.builtin.set_fact:
        join_tkn: "{{ join_token.stdout }}"

    - name: Save join command
      ansible.builtin.set_fact:
        join_cmd: "{{ join_command.stdout }}"
