- name: Control Plane Join
  when:
    - inventory_hostname in groups['k8s_control_plane']
    - not inventory_hostname == groups['k8s_control_plane'][0]
    - not kubernetes_joined
  become: true
  block:
    - name: Run join command on secondary control plane nodes
      ansible.builtin.command: "{{ hostvars[groups['k8s_control_plane'][0]]['join_cmd'] + '--control-plane' }}"
      notify: Delete join token
