- name: Worker tasks
  when:
    - inventory_hostname in groups['k8s_workers']
    - not kubernetes_joined
  become: true
  block:
    - name: Run join command on worker nodes
      ansible.builtin.command: >-
        {{ hostvars[groups['k8s_control_plane'][0]]['join_cmd'] }}
        {% if ignore_preflight_errors is defined and (ignore_preflight_errors | length > 0) %}
        --ignore-preflight-errors={{ ignore_preflight_errors | join(',') }}
        {% endif %}
