- name: Install NFS
  become: true
  tags: [ node-storage, nfs ]
  block:
    - name: Install nfs client
      ansible.builtin.package:
        name: "{{ nfs_pkg_name }}"
        state: present
        update_cache: true
