---
# tasks file for prerequisites

- name: Load common variables
  ansible.builtin.include_vars: "common.yml"

- name: Load OS-family variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include chrony
  ansible.builtin.import_tasks: chrony.yml
