---
# tasks file for sys-prerequisites
- name: Include disable security
  when: not (security_enabled | bool)
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "disable-security-{{ ansible_distribution }}.yml"
        - "disable-security-{{ ansible_os_family }}.yml"
      skip: true

- name: Include disable firewall
  when: not (firewall_enabled | bool)
  ansible.builtin.include_tasks: "disable-firewall.yml"
