- name: Install and configure chrony
  become: true
  tags: [ node_preflight, ntp ]
  block:
    - name: Install chrony
      ansible.builtin.package:
        name: "{{ chrony_pkg_name }}"
        state: present
        update_cache: true

    - name: Start and enable chrony server
      ansible.builtin.service:
        name: "{{ chrony_service_name }}"
        state: started
        enabled: true

    - name: Configure chrony server
      ansible.builtin.template:
        src: chrony.conf.j2
        dest: "{{ chrony_conf_path }}"
        owner: root
        group: root
        mode: '0644'
        backup: yes
      notify: Restart chrony
