- name: Disable selinux
  become: true
  tags: [ node_preflight, security ]
  block:
    - name: Set selinux mode to permissive
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        search_string: "SELINUX=enforcing"
        line: "SELINUX=disabled"
    - name: Disable Selinux 
      ansible.posix.selinux:
        state: disabled

