- name: Set timezone
  become: true
  tags: [ node_preflight, timezone ]
  block:
    - name: Ensure tzdata
      ansible.builtin.package:
        name: tzdata
        state: present
        update_cache: true

    - name: Set timezone
      community.general.timezone:
        name: "{{ timezone }}"
