- name: Configure CRIO for Kubernetes
  become: true
  block:
    - name: Write crio config file
      ansible.builtin.template:
        src: crio-config.conf.j2
        dest: "{{ crio_config_path }}"
        owner: root
        group: root
        mode: "0644"
    - name: Write crio registry config file
      ansible.builtin.template:
        src: crio-registry-conf.j2
        dest: "{{ crio_registry_config_path }}"
        owner: root
        group: root
        mode: "0644"
  notify: "Restart CRI"
