- name: Kubernetes Components Installation
  become: true
  tags: [ k8s-install, k8s-components ]
  block:
    - name: Get K8S Repo Key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key
        dest: /etc/apt/keyrings/k8s.asc
        mode: "0644"

    - name: Add K8S Repo
      ansible.builtin.apt_repository:
        repo: >
          deb [arch={{ "amd64" if ansible_architecture == "x86_64" else "arm64" }}
          signed-by=/etc/apt/keyrings/k8s.asc]
          https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ / 
        filename: k8s
        state: present

    - name: Install K8S Components
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop: "{{ kubernetes_components }}"

    - name: Exclude K8S Components from updates
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop: "{{ kubernetes_components }}"

    - name: Start and Enable Kubelet
      ansible.builtin.service:
        name: kubelet
        state: started
        enabled: true
