---
# tasks file for k8s-install

- name: Load common variables
  ansible.builtin.include_vars: "common.yml"
  tags: [ always ]

- name: Load OS-family variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: true
  tags: [ always ]

- name: Include Kubernetes Install
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "k8s-install-{{ ansible_distribution }}.yml"
        - "k8s-install-{{ ansible_os_family }}.yml"
      skip: true
  tags: [ always ]
