---
# defaults file for node_preflight
ntp_server: "asia.pool.ntp.org"
timezone: "UTC"
dns_servers:
  - "1.1.1.1"
  - "8.8.8.8"
  - "9.9.9.9"
search_domain: "local"
securty_enabled: true
firewall_enabled: true
swap_enabled: false
