- name: Configure kernel modules
  become: true
  tags: [ node-network, kernel ]
  block:

    - name: Load Kernel Modules persistently
      community.general.modprobe:
        name: "{{ item }}"
        state: present
        persistent: present
      loop: "{{ kernel_modules }}"

    - name: Load Additional Kernel Modules persistently
      when: additional_kernel_modules is defined
      community.general.modprobe:
        name: "{{ item }}"
        state: present
        persistent: present
      loop: "{{ additional_kernel_modules }}"
