- name: Configure sysctl
  become: true
  block:
    - name: Load Sysctl Configs Persistently
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: true
      loop: "{{ sysctl_configs | dict2items }}"

    - name: Load Additional Sysctl Configs Persistently
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
        reload: true
      loop: "{{ additional_sysctl_configs | dict2items }}"
